/**
 * Generates a human-readable paragraph explaining why the log was flagged.
 * @param {Object} log - The log object
 * @param {Array} reasons - Array of reason strings generated by the anomaly detector
 * @param {number} score - The calculated anomaly score
 * @param {string} riskLevel - The risk classification
 * @returns {string} Human-readable explanation paragraph
 */
export function generateExplanation(log, reasons, score, riskLevel) {
  let explanation = `This request has been classified as ${riskLevel} with an anomaly score of ${score}/100. `;

  if (score < 30) {
    return explanation + 'No significant anomalies were detected in this log entry.';
  }

  // If there are reasons, compile them into a readable summary.
  if (reasons && reasons.length > 0) {
    const findings = reasons.join(', ').toLowerCase();
    explanation += `The analysis flagged this activity primarily due to factors including ${findings}. `;
    
    // Add contextual recommendation for higher risks
    if (riskLevel === 'High Risk' || riskLevel === 'Critical') {
      explanation += 'Further investigation is recommended to rule out malicious activity or misconfigurations.';
    } else {
      explanation += 'It may be worth reviewing these patterns if they persist over time.';
    }
  }

  return explanation;
}

/**
 * Returns a brief explanation suitable for tabular display or summary views.
 * @param {Array} reasons - Array of reason strings
 * @returns {string} A short, combined reason string
 */
export function generateBriefExplanation(reasons) {
  if (!reasons || reasons.length === 0) {
    return 'Normal behavior';
  }
  return reasons.slice(0, 3).join('; ');
}
